# Generated by Django 2.1.7 on 2019-03-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blob',
            new_name='Blog',
        ),
    ]
